name: CI/CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  IMAGE_URI: ${{ secrets.IMAGE_URI }} # e.g. xxxxx.dkr.ecr.ap-northeast-2.amazonaws.com/crypto-signal-platform

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE_URI:$IMAGE_TAG .
          docker push $IMAGE_URI:$IMAGE_TAG

      - name: Persist image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

  deploy-to-eks:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Replace image tags in k8s manifests
        env:
          IMAGE_TAG: ${{ needs.build-and-push.outputs.image-tag || github.sha }}
          IMAGE_URI: ${{ secrets.IMAGE_URI }}
        run: |
          set -e
          for f in k8s/*.yaml; do
            sed -i "s|image: .*|image: ${IMAGE_URI}:${GITHUB_SHA}|g" "$f"
          done

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/


