apiVersion: batch/v1
kind: CronJob
metadata:
  name: crypto-daily-batch
spec:
  schedule: "0 9 * * *"
  timeZone: Asia/Seoul
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: daily-batch
              image: crypto-signal-platform:latest
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  set -e
                  python upload_s3_feargreed.py && \
                  python upload_s3_upbit.py && \
                  python daily_signal_alarm.py

