apiVersion: batch/v1
kind: CronJob
metadata:
  name: crypto-5min-batch
spec:
  schedule: "*/5 * * * *"
  timeZone: Asia/Seoul
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: upbit-5m
              image: crypto-signal-platform:latest
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  set -e
                  python upload_s3_upbit_5m.py

