apiVersion: v1
kind: Service
metadata:
  name: crypto-webapp-svc
  labels:
    app: crypto-webapp
spec:
  type: LoadBalancer
  selector:
    app: crypto-webapp
  ports:
    - name: http
      port: 80
      targetPort: 8501

